name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install Dependencies
      run: |
        npm ci

    - name: Build Angular Project
      run: |
        npm run build --prod
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifact
        path: |
          dist/angular-to-do
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - run: |
        ls
        
    - name: Checkout Deploy Repository
      uses: actions/checkout@v4
      with:
        repository: ahmetvepayev/ahmetvepayev.github.io
        ref: main
        path: ./deploy
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - run: |
        ls

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: dist-artifact
        path: |
          dist

    - run: |
        ls
        
    - name: Update Deploy Folder
      run: |
        rm -rf ./deploy/docs/*
        
    - run: |
        ls
        
    - run: |
        cp -r dist/* ./deploy/docs/
        
    - run: |
        ls

    - name: Commit and Push Changes
      run: |
        cd ./deploy
        git config user.name "Ahmet Vepayev"
        git config user.email "ahmetwepaogly@gmail.com"
        git add .
        git commit -m "Committed by build-n-deploy"
        git push
